### PR TITLE
gen fake data for perf testing

### PR DESCRIPTION
**Pull request by cmyui**
# Describe your changes

## Checklist
- [ ] I've manually tested my code

### CODE REVIEW

**Comment by GamebP** [comment]
Is this going to work?

**Comment by cmyui** [comment]
Yeah it works -- I used this for #642. I don't plan to merge this, it's pretty hacky lol, just wanted to check the diff.

**Comment by GamebP** [comment]
Hey, do you know why trimming one table, takes a long time to do it. I think my wsl ubuntu is fcked...

**Comment by minisbett** [comment]
> Hey, do you know why trimming one table, takes a long time to do it. I think my wsl ubuntu is fcked...

Not related to this PR or bpy, please ask on the Discord instead or google.
But just drop the table and re-create it.

**Comment by 7ez** [comment]
> > Hey, do you know why trimming one table, takes a long time to do it. I think my wsl ubuntu is fcked...
> 
> Not related to this PR or bpy, please ask on the Discord instead or google. But just drop the table and re-create it.

`DELETE FROM table`:

**Comment by minisbett** [comment]
> > > Hey, do you know why trimming one table, takes a long time to do it. I think my wsl ubuntu is fcked...
> > 
> > Not related to this PR or bpy, please ask on the Discord instead or google. But just drop the table and re-create it.
> 
> `DELETE FROM table`:

that's even slower than truncating because of the way it deallocates + it writes to the undo log

**Comment by 7ez** [comment]
> > > > Hey, do you know why trimming one table, takes a long time to do it. I think my wsl ubuntu is fcked...
> > > 
> > > 
> > > Not related to this PR or bpy, please ask on the Discord instead or google. But just drop the table and re-create it.
> > 
> > 
> > `DELETE FROM table`:
> 
> that's even slower than truncating because of the way it deallocates + it writes to the undo log

If you do it in a transaction then no, lol

**Comment by minisbett** [comment]
> > > > > Hey, do you know why trimming one table, takes a long time to do it. I think my wsl ubuntu is fcked...
> > > > 
> > > > 
> > > > Not related to this PR or bpy, please ask on the Discord instead or google. But just drop the table and re-create it.
> > > 
> > > 
> > > `DELETE FROM table`:
> > 
> > that's even slower than truncating because of the way it deallocates + it writes to the undo log
> 
> If you do it in a transaction then not really lol

I don't think this has anything to do with transactions

**Comment by minisbett** [comment]
> > > > > Hey, do you know why trimming one table, takes a long time to do it. I think my wsl ubuntu is fcked...
> > > > 
> > > > 
> > > > Not related to this PR or bpy, please ask on the Discord instead or google. But just drop the table and re-create it.
> > > 
> > > 
> > > `DELETE FROM table`:
> > 
> > that's even slower than truncating because of the way it deallocates + it writes to the undo log
> 
> If you do it in a transaction then not really lol

I don't think transactions have anything to do with this. On DELETE, every row is locked separately, while TRUNCATE locks the whole table.

**Comment by GamebP** [comment]
truncate tries to delete the data but sometimes gives an error to fix it

**Pull request closed without merging**
