### PR TITLE
add sayo beatmap mirror site support

### PR DESCRIPTION
**Pull request by cdwcgt**
add the support for https://osu.sayobot.cn/
The beatmap mirror site in China

Direct search function not implemented yet

- [x] Ranked status
- [x] keyword search
- [ ] download
- [ ] diff

### CODE REVIEW

**Review by cmyui — APPROVED** [review]
not sure how i didn't notice this

+1 👍🏻

**Review by cmyui — CHANGES_REQUESTED** [review]
oh hahaha, i thought the PR was complete.

if you finish this - we can merge it into master

**Comment by cdwcgt** [comment]
I will try to finish it soon
Thanks for attention

**Comment by cmyui** [comment]
hey - i'm going to close this for the time being

if you'd like to give this another shot, feel free to re-open a pr!

**Pull request closed without merging**
