### PR TITLE
docs: link readme to wiki

### PR DESCRIPTION
**Pull request by NiceAesth**
# Describe your changes

Depends on: 

- [x] #419
- [x] #462
- [x] `BPY_REPO_TOKEN` secret

Transferred content over to the wiki. Changes need to be mirrored in translations. @infernalfire72 @hedgehog-qd 

## Checklist
- [x] The changes pass pre-commit checks (`make lint`)
- [x] The changes follow coding style

### CODE REVIEW

**Comment by NiceAesth** [comment]
drafting until wiki language picker is done

**Comment by minisbett** [comment]
If only github wikis wouldn't suck ass...

**Comment by minisbett** [comment]
besides that looks good

**Comment by cmyui** [comment]
nice work with wiki so far!

**Comment by NiceAesth** [comment]
@7mochi Do you still have the language picker drafts? I would like to get this PR in.

**Comment by 7mochi** [comment]
> @7mochi Do you still have the language picker drafts? I would like to get this PR in.

this? https://github.com/JustArchiNET/ArchiSteamFarm/wiki

**Comment by NiceAesth** [comment]
The wiki changes require a secret token named `BPY_REPO_TOKEN` with at least repo access to both `bancho.py` and `bancho.py.wiki`

**Review by cmyui — APPROVED** [review]

**Pull request merged**
