### PR TITLE
chore: add akatsuki-pp-py from pypi

### PR DESCRIPTION
**Pull request by NiceAesth**
# Describe your changes

## Related Issues / Projects

supersedes #409

## Checklist
- [x] The changes pass pre-commit checks (`make lint`)
- [x] The changes follow coding style

### CODE REVIEW

**Comment by NiceAesth** [comment]
https://github.com/osuAkatsuki/bancho.py/pull/409 :woozy_face:

**Comment by tsunyoku** [comment]
note: the change from git -> pypi means that we now use wheels, so people no longer need to install rust in order to run bancho.py..

**Comment by NiceAesth** [comment]
should i do that in this pr as well ?

**Comment by mayacopeland** [comment]
[ 68747470733a2f2f636174732d646973636f72642e6769746875622e696f2f62616c6c7332312f7374617469632f666173746d657267696e672e676966 ](https://camo.githubusercontent.com/92414bb1b7af756d07d15649e316a08669ba7d198340649382c204b621e5e9b4/68747470733a2f2f636174732d646973636f72642e6769746875622e696f2f62616c6c7332312f7374617469632f666173746d657267696e672e676966) [ ](https://camo.githubusercontent.com/92414bb1b7af756d07d15649e316a08669ba7d198340649382c204b621e5e9b4/68747470733a2f2f636174732d646973636f72642e6769746875622e696f2f62616c6c7332312f7374617469632f666173746d657267696e672e676966)

**Comment by cmyui** [comment]
deferring review to @tsunyoku

**Review by cmyui — APPROVED** [review]

**Review by tsunyoku — APPROVED** [review]

**Pull request merged**
