### PR TITLE
Change avatar serving to be done through NGINX

### PR DESCRIPTION
**Pull request by Airiuwu**
Why go through nginx to get to code to serve an avatar when you can just go to nginx to serve it?

### CODE REVIEW

**Comment by 7ez** [comment]
because gif support

**Comment by Airiuwu** [comment]
gifs cant work in game so no point

**Comment by 7ez** [comment]
they can on website

**Comment by minisbett** [comment]
And this way you get much better control over serving avatars, as well as providing much more possibility for customization or adjustment. Yes, not many people will change something on bpy but why would you change it when it has no disadvantage, just that tiny advantage? Seems like pointless effort to me without any effect on the outcome.
Another disadvantage is the inconvenience of using bpy with other webservers besides nginx since then you'd have to find out how a config file for that would look like, if the webserver even can provide that functionality (which most big webservers like apache do tho).

Personally I'd say that this is something that should be included in the bpy code such that it can be seen as a whole independent from any third party software. But this opinion on how to structure a project and it's infrastructure of functionality varies from developer to developer.

**Comment by cmyui** [comment]
hey i'll be doing this in my refactor branch, #205 along with some other improvements to nginx - i'll reach out shortly if you'd like to move this PR over to that branch

**Comment by cmyui** [comment]
changes look good though

**Comment by cmyui** [comment]
open something like this (tested) to #205 and i'll merge it

**Pull request closed without merging**
