### PR TITLE
Cmd

### PR DESCRIPTION
**Pull request by KyuubiRan**

### CODE REVIEW

**Comment by minisbett** [comment]
literally what is your mission with that commit, I'm pretty sure commands like "silenceuid" won't be added

**Comment by minisbett** [comment]
image

**Comment by minisbett** [comment]
Also you commited weird stuff that is not supposed to be in this repo

**Comment by lenforiee** [comment]
they closed a pull request & their fork is private so it was most likely github being weird and merging to real (cmyui) repo instead of private one

**Comment by minisbett** [comment]
lmao lets yoink the osu tools code so we have proper pp calc

**Comment by minisbett** [comment]
and the multitask recalc

**Comment by alowave223** [comment]
Why you so annoying

**Comment by memsdm05** [comment]
comedy

**Pull request closed without merging**
