### PR TITLE
Refactoring of pp calculation into a functional api, reused across codebase

### PR DESCRIPTION
**Pull request by cmyui**
this pr is mostly just to clean up usecases of pp calculation (as there's currently a lot of logic duplication), and to decouple logic from controllers (mainly endpoints)

also, this provides an API to gulag's pp calculation that you can quite easily use yourself; a simple example,
```py
Python 3.9.10+ (main, Feb 24 2022, 08:53:15) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from app.utils import calculate_performances
>>> 
>>> results = calculate_performances(
...     osu_file_path='/home/cmyui/programming/gulag/.data/osu/93842.osu',
...     mode=0,
...     mods=64,
...     scores=[{"acc": 93.12, "combo": 312}, {"acc": 96.32, "combo": 69}],
... )
>>> 
>>> results
[{'performance': 168.92620849609375, 'star_rating': 7.371907711029053}, {'performance': 75.38504791259766, 'star_rating': 7.371907711029053}]```

### CODE REVIEW

**Comment by cmyui** [comment]
this still needs test suite

**Comment by cmyui** [comment]
this still needs test suite

**Comment by 7ez** [comment]
this still needs test suite

**Review by tsunyoku — APPROVED** [review]
all looks good to me, can't see anything to comment on :D

**Comment by cmyui** [comment]
yolo

**Pull request merged**
