### PR TITLE
Add mod introduction achievements

### PR DESCRIPTION
**Pull request by depreciate**

### CODE REVIEW

**Review by tsunyoku — CHANGES_REQUESTED** [review]
you’ll need to add migrations for these

**Comment by cmyui** [comment]
looks good from my perspective - @tsunyoku any thoughts?

**Review by cmyui — APPROVED** [review]

**Comment by 7ez** [comment]
Bruh my review didnt go thru

**Comment by 7ez** [comment]
Oh well cmyui already did the thing

**Pull request merged**
