### PR TITLE
optimization for donator info in !user command

### PR DESCRIPTION
**Pull request by minisbett**

### CODE REVIEW

**Comment by cmyui** [comment]
can u pls just name things what they actually are, it just ruins the log of commits/requests - treat git commit names, comments, pr names as logs

**Comment by cmyui** [comment]
i won't really like squash merging commits but i do it in these cases to keep the log clean
image

**Comment by cmyui** [comment]
i'm glad you're helping out - i don't mean to set the wrong tone but i try my best to keep it clean :^)

**Comment by minisbett** [comment]
sure sure I just got kinda lazy because it was such a small change

**Pull request merged**
