### PR TITLE
chore: upgrade to python 3.11; upgrade redis library; upgrade databases

### PR DESCRIPTION
**Pull request by 7mochi**
# Describe your changes

## Checklist
- [x] I've manually tested my code
  - [x] Make install
  - [x] Make install-dev
  - [x] Make run
  - [x] Login
  - [x] Commands
    - [x] Help
    - [x] Roll
    - [x] API Key
    - [x] Block/Unblock
    - [x] Reconnect
    - [x] Maplink
    - [x] Recent
    - [x] Top
    - [x] With
    - [x] Request
    - [x] Requests
    - [x] Map Rank/Unrank/Love Map/Set
    - [x] Notes
    - [x] Add note
    - [x] Server
    - [x] Menu 
    - [x] Addpriv
    - [x] Rmpriv
    - [x] Givedonator
    - [x] Stealth
    - [x] Switch server
    - [x] Alert
    - [x] Alert user
  - [x] Submit plays
    - [x] vn!std
    - [x] vn!taiko
    - [x] vn!ctb
    - [x] vn!ctb
    - [x] rx!std
    - [x] rx!taiko
    - [x] rx!ctb
    - [x] ap!std
    - [x] ap!ctb
    - [x] ap!mania
  - [x] Multiplayer
- [x] The changes pass pre-commit checks (`make lint`)
- [x] The changes follow coding style

### CODE REVIEW

**Comment by NiceAesth** [comment]
I would hope you didn't do this manually but looking at the fact you didn't change pyupgrade from 37-plus to 311-plus does not inspire confidence

**Comment by NiceAesth** [comment]
> > I would hope you didn't do this manually but looking at the fact you didn't change pyupgrade from 37-plus to 311-plus does not inspire confidence
> 
> I just modified the Pipfile and let the lock file regenerate, is there anything i forgot to modify or should do differently?

should update pre-commit pyupgrade args to do 311

**Comment by NiceAesth** [comment]
also, this definitely needs to be tested

**Comment by 7mochi** [comment]
> > > I would hope you didn't do this manually but looking at the fact you didn't change pyupgrade from 37-plus to 311-plus does not inspire confidence
> > 
> > 
> > I just modified the Pipfile and let the lock file regenerate, is there anything i forgot to modify or should do differently?
> 
> should update pre-commit pyupgrade args to do 311

done, i need testers :3

**Comment by NiceAesth** [comment]
https://github.com/osuAkatsuki/bancho.py/pull/493 will change deps

**Comment by NiceAesth** [comment]
can you fix conflicts? want to get this merged. @7mochi 

also, python 3.12 is very close to releasing as well. should be looking into that after this PR (especially typing changes)

**Review by NiceAesth — APPROVED** [review]
dismissing

**Review by NiceAesth — CHANGES_REQUESTED** [review]
changes need to be tested further

**Review by NiceAesth — APPROVED** [review]
seems to work fine. further testing is welcomed.

loc balooned up due to auto-formatting bump to py3.11

**Comment by cmyui** [comment]
:fire: nice work

**Pull request merged**
