### PR TITLE
Add tail to make logs

### PR DESCRIPTION
**Pull request by minisbett**
# Describe your changes

The current `make logs` command causes it to print out the whole log since container start, which feels very awful to use. Adding `--tail 1` causes it to start all the way at the bottom, which I think is preferred.

## Checklist
- [x] I've manually tested my code

### CODE REVIEW

**Comment by tsunyoku** [comment]
meh, this is pure opinion at this point -- i often like to have atleast *some* history of prior logs. i think make lets you pass parameters after the action and it gets passed to what it executes? that would be the best way to handle this

**Comment by NiceAesth** [comment]
`--follow` would probably be a better default

**Comment by minisbett** [comment]
> meh, this is pure opinion at this point -- i often like to have atleast _some_ history of prior logs. i think make lets you pass parameters after the action and it gets passed to what it executes? that would be the best way to handle this

make unfortunately doesn't, afaik it's awful in terms of argument parsing. You could do smth like `make logs last=100` for example I think but directly specifying it like `make logs 100` doesn't work.

If my bpy runs over a day I need to wait many minutes for the logs to reach the bottom, therefore the current command is pretty much unusable.

**Comment by minisbett** [comment]
> `--follow` would probably be a better default

This is the current behavior. But as I said before, it makes the command pretty useless if u need to wait literal minutes until u see somewhat recent logs.

**Comment by tsunyoku** [comment]
> You could do smth like make logs last=100 for example I think but directly specifying it like make logs 100 doesn't work.

`last=100` is fine. better than nothing. certainly better than defining my behaviour for me

**Review by cmyui — APPROVED** [review]
+1 👍🏻

**Pull request merged**
